version: "3.9"

# NOTE: This _has _to start with `x-`
x-logging: &default-logging
  options:
    max-size: "20k"
    max-file: "10"

services:
  app: &api
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    command: uvicorn main:app --reload
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000
    depends_on:
      - db
    stdin_open: true
    tty: true
    logging: *default-logging

  db:
    image: mysql:5.7
    container_name: db
    env_file:
      - .env
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpass
    #   MYSQL_DATABASE: mysqldb
    #   MYSQL_USER: mysqluser
    #   MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    tty: true
    logging: *default-logging


  #-----------------------------------------------
  #   Rabbitmq & Flower monitoring tool
  #-----------------------------------------------
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3.6-management
    # setting hostname here makes data persist properly between
    # containers being destroyed..!
    hostname: rabbit
    env_file:
      - .env
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
      - ${RABBITMQ_PORT}:5672
    volumes:
      - ./var/rabbit:/var/lib/rabbitmq
    restart: unless-stopped
    logging:
      options:
        max-size: "20k"
        max-file: "10"

  flower:
    container_name: flower
    image: mher/flower:0.9.7
    env_file:
      - .env
    environment:
      - FLOWER_BASIC_AUTH=guest:guest
      - CELERY_BROKER_URL=pyamqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}//
    restart: unless-stopped
    ports:
      - ${FLOWER_PUBLIC_PORT:-5555}:5555
    logging:
      options:
        max-size: "20k"
        max-file: "10"


  #-----------------------------------------------
  #   Celery Service
  #-----------------------------------------------
  celery:
    restart: always
    <<: *api
    container_name: worker
    # command: >
    #   sh -c "celery -A project worker --loglevel=INFO"
    ports: []
    depends_on:
      - rabbit
      - db
    logging:
      options:
        max-size: "20k"
        max-file: "10"
